name: men_u
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  badges: ^3.1.2
  fetch_client: ^1.0.2
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0
  pusher_channels_flutter: ^2.2.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Cooking.gif
